In [1]:
import pandas as pd
import numpy as np

In [2]:
%ls datasets

adult.csv
airline_data.csv
antropometria00.csv
antropometria-dataset.csv
Book3.csv
Canada.xlsx
Cartwheeldata.csv
census.csv
coches.csv
COVID-19_Daily_Counts_of_Cases__Hospitalizations__and_Deaths.csv
cwurData.csv
data.csv
headbrain.csv
mic2.xlsx
mic.xlsx
movies.csv
nhanes_2015_2016.csv
pokemon.csv
reg_data.csv
sample_pivot.csv
tips.csv
weight-height.csv

In [3]:
df = pd.read_csv("datasets/COVID-19_Daily_Counts_of_Cases__Hospitalizations__and_Deaths.csv")
df.head(2)

,DATE_OF_INTEREST,CASE_COUNT,probable_case_count,HOSPITALIZED_COUNT,DEATH_COUNT,DEATH_COUNT_PROBABLE,CASE_COUNT_7DAY_AVG,all_case_count_7day_avg,HOSP_COUNT_7DAY_AVG,DEATH_COUNT_7DAY_AVG,...,si_probable_case_count,SI_HOSPITALIZED_COUNT,SI_DEATH_COUNT,si_probable_death_count,SI_CASE_COUNT_7DAY_AVG,si_all_case_count_7day_avg,SI_HOSPITALIZED_COUNT_7DAY_AVG,SI_DEATH_COUNT_7DAY_AVG,si_all_death_count_7day_avg,INCOMPLETE
0,02/29/2020,1,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,03/01/20,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
df.describe()

,CASE_COUNT,probable_case_count,HOSPITALIZED_COUNT,DEATH_COUNT,DEATH_COUNT_PROBABLE,CASE_COUNT_7DAY_AVG,all_case_count_7day_avg,HOSP_COUNT_7DAY_AVG,DEATH_COUNT_7DAY_AVG,all_death_count_7day_avg,...,si_probable_case_count,SI_HOSPITALIZED_COUNT,SI_DEATH_COUNT,si_probable_death_count,SI_CASE_COUNT_7DAY_AVG,si_all_case_count_7day_avg,SI_HOSPITALIZED_COUNT_7DAY_AVG,SI_DEATH_COUNT_7DAY_AVG,si_all_death_count_7day_avg,INCOMPLETE
count,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,...,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000,731.000000
mean,2652.082079,465.993160,201.128591,46.898769,7.545828,2650.073871,3115.744186,201.079343,46.846785,54.398085,...,30.518468,11.625171,2.804378,0.318741,193.930233,224.462380,11.616963,2.777018,3.097127,581.833105
std,6033.148680,748.807122,294.289132,90.812335,27.734337,5548.073748,6207.994833,289.115878,89.739294,115.934944,...,41.445103,13.784511,4.477191,1.137609,362.341448,396.652769,13.254555,4.185208,5.114859,5921.284795
min,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,412.500000,42.000000,42.000000,7.000000,0.000000,427.000000,503.500000,42.000000,7.000000,8.000000,...,2.000000,3.000000,0.000000,0.000000,30.000000,34.500000,3.000000,0.000000,1.000000,0.000000
50%,1057.000000,227.000000,84.000000,14.000000,1.000000,1119.000000,1447.000000,87.000000,13.000000,14.000000,...,16.000000,6.000000,1.000000,0.000000,93.000000,112.000000,6.000000,1.000000,1.000000,0.000000
75%,2790.000000,603.500000,261.500000,52.000000,3.000000,2844.500000,3615.500000,269.500000,52.000000,54.000000,...,47.000000,16.500000,4.000000,0.000000,219.000000,272.000000,17.000000,4.000000,4.000000,0.000000
max,54767.000000,5889.000000,1850.000000,598.000000,227.000000,39248.000000,43736.000000,1669.000000,566.000000,762.000000,...,317.000000,83.000000,34.000000,9.000000,2667.000000,2886.000000,72.000000,26.000000,33.000000,60760.000000

In [5]:
pd.pivot_table(df,
 index = ['DATE_OF_INTEREST'],
 aggfunc = ['median', 'mean'],
 values = ['CASE_COUNT','HOSPITALIZED_COUNT','DEATH_COUNT'],
 margins = True
 )

                     median                                         mean  \
                 CASE_COUNT DEATH_COUNT HOSPITALIZED_COUNT    CASE_COUNT
DATE_OF_INTEREST
01/01/21               1340          36                301   1340.000000
01/01/22              12002          56                859  12002.000000
01/02/21               4202          57                326   4202.000000
01/02/22              32377          62               1295  32377.000000
01/03/21               3465          38                302   3465.000000
...                     ...         ...                ...           ...
12/30/2020             4985          40                316   4985.000000
12/30/2021            47056          35               1022  47056.000000
12/31/2020             3393          41                284   3393.000000
12/31/2021            29002          54                816  29002.000000
All                    1057          14                 84   2652.082079


                 DEATH_COUNT HOSPITALIZED_COUNT
DATE_OF_INTEREST
01/01/21           36.000000         301.000000
01/01/22           56.000000         859.000000
01/02/21           57.000000         326.000000
01/02/22           62.000000        1295.000000
01/03/21           38.000000         302.000000
...                      ...                ...
12/30/2020         40.000000         316.000000
12/30/2021         35.000000        1022.000000
12/31/2020         41.000000         284.000000
12/31/2021         54.000000         816.000000
All                46.898769         201.128591

[732 rows x 6 columns]

In [6]:
df[['CASE_COUNT','DEATH_COUNT','HOSPITALIZED_COUNT']].describe()

         CASE_COUNT  DEATH_COUNT  HOSPITALIZED_COUNT
count    731.000000   731.000000          731.000000
mean    2652.082079    46.898769          201.128591
std     6033.148680    90.812335          294.289132
min        0.000000     0.000000            1.000000
25%      412.500000     7.000000           42.000000
50%     1057.000000    14.000000           84.000000
75%     2790.000000    52.000000          261.500000
max    54767.000000   598.000000         1850.000000

In [7]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,721,722,723,724,725,726,727,728,729,730
DATE_OF_INTEREST,02/29/2020,03/01/20,03/02/20,03/03/20,03/04/20,03/05/20,03/06/20,03/07/20,03/08/20,03/09/20,...,02/19/2022,02/20/2022,02/21/2022,02/22/2022,02/23/2022,02/24/2022,02/25/2022,02/26/2022,02/27/2022,02/28/2022
CASE_COUNT,1,0,0,1,5,3,8,7,21,57,...,423,378,541,671,687,638,499,321,346,627
probable_case_count,0,0,0,0,0,0,0,0,0,0,...,70,57,90,91,69,83,36,81,69,95
HOSPITALIZED_COUNT,1,1,2,7,2,14,8,8,18,37,...,44,32,40,45,35,31,25,3,4,1
DEATH_COUNT,0,0,0,0,0,0,0,0,0,0,...,28,15,25,12,16,15,11,5,11,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
si_all_case_count_7day_avg,0,0,0,0,0,0,0,0,0,1,...,59,58,53,50,47,46,43,41,40,41
SI_HOSPITALIZED_COUNT_7DAY_AVG,0,0,0,0,0,0,0,0,0,1,...,5,4,4,4,3,3,3,3,2,2
SI_DEATH_COUNT_7DAY_AVG,0,0,0,0,0,0,0,0,0,0,...,2,2,2,1,1,1,1,1,1,1
si_all_death_count_7day_avg,0,0,0,0,0,0,0,0,0,0,...,2,2,2,1,1,2,1,1,1,1
INCOMPLETE,0,0,0,0,0,0,0,0,0,0,...,0,0,0,60760,60760,60760,60760,60760,60760,60760

In [8]:
df.columns

Index(['DATE_OF_INTEREST', 'CASE_COUNT', 'probable_case_count',
       'HOSPITALIZED_COUNT', 'DEATH_COUNT', 'DEATH_COUNT_PROBABLE',
       'CASE_COUNT_7DAY_AVG', 'all_case_count_7day_avg', 'HOSP_COUNT_7DAY_AVG',
       'DEATH_COUNT_7DAY_AVG', 'all_death_count_7day_avg', 'BX_CASE_COUNT',
       'bx_probable_case_count', 'BX_HOSPITALIZED_COUNT', 'BX_DEATH_COUNT',
       'bx_probable_death_count', 'BX_CASE_COUNT_7DAY_AVG',
       'bx_all_case_count_7day_avg', 'BX_HOSPITALIZED_COUNT_7DAY_AVG',
       'BX_DEATH_COUNT_7DAY_AVG', 'bx_all_death_count_7day_avg',
       'BK_CASE_COUNT', 'bk_probable_case_count', 'BK_HOSPITALIZED_COUNT',
       'BK_DEATH_COUNT', 'bk_probable_death_count', 'BK_CASE_COUNT_7DAY_AVG',
       'bk_all_case_count_7day_avg', 'BK_HOSPITALIZED_COUNT_7DAY_AVG',
       'BK_DEATH_COUNT_7DAY_AVG', 'bk_all_death_count_7day_avg',
       'MN_CASE_COUNT', 'mn_probable_case_count', 'MN_HOSPITALIZED_COUNT',
       'MN_DEATH_COUNT', 'mn_probable_death_count', 'MN_CASE_COUNT_7DAY_AVG',
       'mn_all_case_count_7day_avg', 'MN_HOSPITALIZED_COUNT_7DAY_AVG',
       'MN_DEATH_COUNT_7DAY_AVG', 'mn_all_death_count_7day_avg',
       'QN_CASE_COUNT', 'qn_probable_case_count', 'QN_HOSPITALIZED_COUNT',
       'QN_DEATH_COUNT', 'qn_probable_death_count', 'QN_CASE_COUNT_7DAY_AVG',
       'qn_all_case_count_7day_avg', 'QN_HOSPITALIZED_COUNT_7DAY_AVG',
       'QN_DEATH_COUNT_7DAY_AVG', 'qn_all_death_count_7day_avg',
       'SI_CASE_COUNT', 'si_probable_case_count', 'SI_HOSPITALIZED_COUNT',
       'SI_DEATH_COUNT', 'si_probable_death_count', 'SI_CASE_COUNT_7DAY_AVG',
       'si_all_case_count_7day_avg', 'SI_HOSPITALIZED_COUNT_7DAY_AVG',
       'SI_DEATH_COUNT_7DAY_AVG', 'si_all_death_count_7day_avg', 'INCOMPLETE'],
      dtype='object')

In [9]:
df.drop(['probable_case_count','CASE_COUNT_7DAY_AVG', 'all_case_count_7day_avg', 'HOSP_COUNT_7DAY_AVG',
       'DEATH_COUNT_7DAY_AVG', 'all_death_count_7day_avg', 'BX_CASE_COUNT',
       'bx_probable_case_count', 'BX_HOSPITALIZED_COUNT', 'BX_DEATH_COUNT',
       'bx_probable_death_count', 'BX_CASE_COUNT_7DAY_AVG',
       'bx_all_case_count_7day_avg', 'BX_HOSPITALIZED_COUNT_7DAY_AVG',
       'BX_DEATH_COUNT_7DAY_AVG', 'bx_all_death_count_7day_avg',
       'BK_CASE_COUNT', 'bk_probable_case_count', 'BK_HOSPITALIZED_COUNT',
       'BK_DEATH_COUNT', 'bk_probable_death_count', 'BK_CASE_COUNT_7DAY_AVG',
       'bk_all_case_count_7day_avg', 'BK_HOSPITALIZED_COUNT_7DAY_AVG',
       'BK_DEATH_COUNT_7DAY_AVG', 'bk_all_death_count_7day_avg',
       'MN_CASE_COUNT', 'mn_probable_case_count', 'MN_HOSPITALIZED_COUNT',
       'MN_DEATH_COUNT', 'mn_probable_death_count', 'MN_CASE_COUNT_7DAY_AVG',
       'mn_all_case_count_7day_avg', 'MN_HOSPITALIZED_COUNT_7DAY_AVG',
       'MN_DEATH_COUNT_7DAY_AVG', 'mn_all_death_count_7day_avg',
       'QN_CASE_COUNT', 'qn_probable_case_count', 'QN_HOSPITALIZED_COUNT',
       'QN_DEATH_COUNT', 'qn_probable_death_count', 'QN_CASE_COUNT_7DAY_AVG',
       'qn_all_case_count_7day_avg', 'QN_HOSPITALIZED_COUNT_7DAY_AVG',
       'QN_DEATH_COUNT_7DAY_AVG', 'qn_all_death_count_7day_avg',
       'SI_CASE_COUNT', 'si_probable_case_count', 'SI_HOSPITALIZED_COUNT',
       'SI_DEATH_COUNT', 'si_probable_death_count', 'SI_CASE_COUNT_7DAY_AVG',
       'si_all_case_count_7day_avg', 'SI_HOSPITALIZED_COUNT_7DAY_AVG',
       'SI_DEATH_COUNT_7DAY_AVG', 'si_all_death_count_7day_avg', 'INCOMPLETE',],
        axis = 1,
        inplace = True
       )

In [10]:
df.head(2)

,DATE_OF_INTEREST,CASE_COUNT,HOSPITALIZED_COUNT,DEATH_COUNT,DEATH_COUNT_PROBABLE
0,02/29/2020,1,1,0,0
1,03/01/20,0,1,0,0

In [11]:
import matplotlib as mpl
import matplotlib.pyplot as plt

In [12]:
mpl.style.use('classic')

In [13]:
print(plt.style.available)

['Solarize_Light2', '_classic_test_patch', 'bmh', 'classic', 'dark_background', 'fast', 'fivethirtyeight', 'ggplot', 'grayscale', 'seaborn', 'seaborn-bright', 'seaborn-colorblind', 'seaborn-dark', 'seaborn-dark-palette', 'seaborn-darkgrid', 'seaborn-deep', 'seaborn-muted', 'seaborn-notebook', 'seaborn-paper', 'seaborn-pastel', 'seaborn-poster', 'seaborn-talk', 'seaborn-ticks', 'seaborn-white', 'seaborn-whitegrid', 'tableau-colorblind10']

In [14]:
#c19 = df.sort_values(['DATE_OF_INTEREST'], ascending = False, axis = 0)

In [15]:
pd.pivot_table(df,
 index = ['DATE_OF_INTEREST'],
 aggfunc = ['median', 'mean'],
 values = ['CASE_COUNT','HOSPITALIZED_COUNT','DEATH_COUNT'],
 margins = True
 )

                     median                                         mean  \
                 CASE_COUNT DEATH_COUNT HOSPITALIZED_COUNT    CASE_COUNT
DATE_OF_INTEREST
01/01/21               1340          36                301   1340.000000
01/01/22              12002          56                859  12002.000000
01/02/21               4202          57                326   4202.000000
01/02/22              32377          62               1295  32377.000000
01/03/21               3465          38                302   3465.000000
...                     ...         ...                ...           ...
12/30/2020             4985          40                316   4985.000000
12/30/2021            47056          35               1022  47056.000000
12/31/2020             3393          41                284   3393.000000
12/31/2021            29002          54                816  29002.000000
All                    1057          14                 84   2652.082079


                 DEATH_COUNT HOSPITALIZED_COUNT
DATE_OF_INTEREST
01/01/21           36.000000         301.000000
01/01/22           56.000000         859.000000
01/02/21           57.000000         326.000000
01/02/22           62.000000        1295.000000
01/03/21           38.000000         302.000000
...                      ...                ...
12/30/2020         40.000000         316.000000
12/30/2021         35.000000        1022.000000
12/31/2020         41.000000         284.000000
12/31/2021         54.000000         816.000000
All                46.898769         201.128591

[732 rows x 6 columns]

In [19]:
c19 = df.transpose()

In [20]:
c19.plot(figsize = (20,10))
plt.xlabel('Date', fontsize = 17)
plt.xticks(fontsize = 17, rotation = 45)
plt.ylabel('Cases', fontsize = 17)
plt.yticks(fontsize = 17)
plt.title('Case count', fontsize = 17)

TypeError: no numeric data to plot

# Description of the data

In this dataset we can see the daily count of COVID 19 cases, hospitalizations and deaths in Oceania. In the variables we can observe the day, death count, hospitalizations and cases, there is also a probable number of the same issues, this is because there may be cases that were not counted due to lack of information, etc. There are also variables in which we can observe the same theme but obtained weekly.

All variables are numeric, discrete, only the date is a string, ordinal.

In [ ]:
classic